[build]
  command   = "echo \"const SUPABASE_URL='$SUPABASE_URL'; const SUPABASE_ANON_KEY='$SUPABASE_ANON_KEY';\" > config.js"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/lab"
  to   = "/lab/index.html"
  status = 200

[[redirects]]
  from = "/lab/LAB-birthday-greetings"
  to   = "/lab/LAB-birthday-greetings/index.html"
  status = 200
